apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cmtvb3Rhc3N3b3Jk  # Base64-encoded: "rootpassword"
  MYSQL_DATABASE: YXBwX2Ri  # Base64-encoded: "app_db"
